### ISSUE TITLE
Failed to access sysfs for card 'card0

### ISSUE THREAD

**Issue by knuxyl** [nowrep/amdgpufan#1]
sudo amdgpufan -d
D: Using card 'card0' with 6 fan curve entries
Failed to access sysfs for card 'card0

I looked through the source code and it's failing to find the gpu_metrics file because I don't have it. I guess I did before I reinstalled Debian because it was working fine. If you know what provides this functionality it would be great to put it in the readme. All drivers for amdgpu are installed so I'm not sure what's going on. Thanks

I'd prefer this simple program versus all the python crap elsewhere.

**Comment by nowrep** [comment]
Are you sure your Radeon card is actually `card0`?

**Comment by knuxyl** [comment]
> Are you sure your Radeon card is actually `card0`?

Well it's actually card1, I verified that before. But neither of the cards have the gpu_metrics file. I have an iGPU (P630) and the Radeon (WX 4100). There's some package that supplied the gpu_metrics file and I assumed it was just the driver and even documentation suggested it but I just don't have it. I'm using the same Debian installation I had running earlier too.

**Comment by knuxyl** [comment]
Well it's actually card1, I verified that before. But neither of the cards have the gpu_metrics file. I have an iGPU (P630) and the Radeon (WX 4100). There's some package that supplied the gpu_metrics file and I assumed it was just the driver and even documentation suggested it but I just don't have it. I'm using the same Debian installation I had running earlier too. My Radeon has 4xDP and so does card1. Card0 has 3xDP and 3xHDMI and my onboard graphics has 3xDP so I'm 100% sure card1 is my Radeon. But either way, neither card0 or card1 worked, both had same error. The hwmon looks to be there, just no the gpu_metrics. I also ran a fulkl system scan and there isn't a file gpu_metrics on my system anywhere.

```
ls -la /sys/class/drm/card1/device/ | sed 's/^.* //g'

>aer_dev_correctable
aer_dev_fatal
aer_dev_nonfatal
ari_enabled
boot_vga
broken_parity_status
class
config
consistent_dma_mask_bits
../../../virtual/devlink/pci:0000:01:00.0--pci:0000:01:00.1
current_link_speed
current_link_width
d3cold_allowed
device
dma_mask_bits
../../../../bus/pci/drivers/amdgpu
driver_override
drm
enable
../../../LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:13/device:14
fw_version
gpu_busy_percent
graphics
hwmon
i2c-10
i2c-11
i2c-8
i2c-9
../../../virtual/iommu/dmar1
../../../../kernel/iommu_groups/2
irq
link
local_cpulist
local_cpus
max_link_speed
max_link_width
mem_busy_percent
mem_info_gtt_total
mem_info_gtt_used
mem_info_preempt_used
mem_info_vis_vram_total
mem_info_vis_vram_used
mem_info_vram_total
mem_info_vram_used
mem_info_vram_vendor
modalias
msi_bus
msi_irqs
numa_node
pcie_bw
pcie_replay_count
power
power_dpm_force_performance_level
power_dpm_state
power_state
pp_cur_state
pp_dpm_mclk
pp_dpm_pcie
pp_dpm_sclk
pp_force_state
pp_mclk_od
pp_num_states
pp_power_profile_mode
pp_sclk_od
pp_table
product_name
product_number
remove
rescan
reset
reset_method
resource
resource0
resource0_resize
resource0_wc
resource2
resource2_wc
resource4
resource5
revision
rom
serial_number
../../../../bus/pci
subsystem_device
subsystem_vendor
thermal_throttling_logging
uevent
vbios_version
vendor
```

And I know the gpu driver is correctly being used

> Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon Pro WX 4100 (polaris11, LLVM 15.0.6, DRM 3.49, 6.1.0-2-amd64) (0x67e3)
    Version: 22.3.3
    Accelerated: yes
    Video memory: 4096MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2

**Comment by knuxyl** [comment]
[ca2381a](https://github.com/nowrep/amdgpufan/commit/ca2381aad35a4dab0962d5ce6dad91f33fada4f1) fixed the problem. Thanks!

**Comment by knuxyl** [comment]
Actually somethings going on now, the fan is spinning up to like 100% at around 43 C with this configuration

```
# card
card1
# temperature fanspeed
30 20
40 30
50 40
60 60
70 80
80 100
```

> amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:      750.00 mV 
fan1:        3968 RPM  (min = 1600 RPM, max = 6000 RPM)
edge:         +42.0°C  (crit = +99.0°C, hyst = -273.1°C)
PPT:          14.15 W  (cap =  35.00 W)

> amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:      750.00 mV 
fan1:        6090 RPM  (min = 1600 RPM, max = 6000 RPM)
edge:         +43.0°C  (crit = +99.0°C, hyst = -273.1°C)
PPT:          13.11 W  (cap =  35.00 W)

**Comment by nowrep** [comment]
I've force pushed and edited the commit, so make sure you build again.
The original commit had wrong temperature calculations, so the fan would never spin up (or stay at max).

**Comment by knuxyl** [comment]
> 

I'm still getting 100% fan speed right at 43C.

**Comment by nowrep** [comment]
Please run with debug logging: `amdgpufan -d` and also show output of `sensors`

**Comment by knuxyl** [comment]
```
D: 41 ˚C -> 31
D: 42 ˚C -> 32
D: 43 ˚C -> 33
D: 42 ˚C -> 32
D: 43 ˚C -> 33
D: 44 ˚C -> 34
D: 45 ˚C -> 35
D: 46 ˚C -> 36
```
```
amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:      750.00 mV 
fan1:        3393 RPM  (min = 1600 RPM, max = 6000 RPM)
edge:         +45.0°C  (crit = +99.0°C, hyst = -273.1°C)
PPT:          13.01 W  (cap =  35.00 W)
```
It seems it is setting the values for the fan speed correctly, but 35% of 6000 shouldn't be 3393. I think the problem is at the setting the fan speed.
Running the application standalone is producing different results from the systemd service though, although fan speed is still innacurate, it's not pushing 100% at 43C. I'm not sure what's happening. I'll recheck the make install and make sure it's actually copying the newly built binary

Just checked, not really a problem but it's installing the service to "//usr/lib/systemd/system/amdgpufan.service" Because of
`install -D -m 644 -p $(TARGET).service $(DESTDIR)/$(SYSTEMD_UNIT_PATH)/$(TARGET).service`
The "/" between DESTDIR and SYSTEMD_UNIT_PATH is adding an unnessacery "/".

**Comment by knuxyl** [comment]
Systemd is now behaving like the standalone, but percentage of fan speed is still off. I don't know how or why. 
35% fan speed is pushing 3410 rpm out of max 6000.

**Comment by nowrep** [comment]
You will have to lower the values in config then.

Is it possible that you are on newer kernel which behaves differently? There has been recent fan pwm changes in amdgpu, but I'm not sure if those were for your gpu model.

Also `PWM = 0` equals `1600 RPM` for you. So it looks correct that PWM 35 => 3400 RPM.

**Comment by knuxyl** [comment]
More than likely, I am on Debian Testing, linux-6.1.0-2-amd64.
And how do you know PWM 0 is 1600 RPM?

**Comment by nowrep** [comment]
`fan1:        3393 RPM  (min = 1600 RPM, max = 6000 RPM)`

**Comment by knuxyl** [comment]
> 

lol ok. I'll just adjust my configuration appropriately. And thanks again for putting this together, these workstation cards idle at like 65C and it doesn't help I have a SFF case with barely any airflow.
